import { Schema, model } from "mongoose";
import { usersSchemaType } from "./types";

const UsersSchema = new Schema(
  {
    username: {
      type: String,
      required: true,
      unique: true,
      sparse: true,
      trim: true,
      lowercase: true,
    },
    firstName: {
      type: String,
      required: true,
      trim: true,
    },
    lastName: {
      type: String,
      required: true,
      trim: true,
    },
    companyId: {
      type: String,
    },
    name: {
      type: String,
    },
    picture: {
      type: String,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      sparse: true,
      lowercase: true,
      trim: true,
    },
    password: {
      type: String,
      required: true,
    },
    phone: {
      type: String,
      required: true,
      unique: true,
      sparse: true,
    },
    address: {
      type: String,
    },
    country: {
      type: String,
    },
    role: {
      type: String,
      default: "admin",
    },
    roles: {
      type: [String],
      default: ["admin"],
    },
    lastLogin: {
      type: Date,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    deletedAt: {
      type: Date,
      default: null,
    },
    deletedBy: {
      type: Schema.Types.ObjectId,
      ref: "Users",
      default: null,
    },
  },
  {
    timestamps: { createdAt: "createdAt", updatedAt: "updatedAt" },
  },
);

export const UsersModel = model<usersSchemaType>("Users", UsersSchema);

// // Users
// const anyUser = [{
//   username: "superadmin",
//   email: "admin@example.com",
//   password: "StagingSeedAdmin_ChangeMe_2026!",
//   role: "super_admin",
// },
// {
//   username: "jAkmel",
//   email: "jkmael24@ashiverb-security.com",
//   password: "Nolly@34r@",
//   role: "admin",
// },
// {
//   username: "bpelumi",
//   email: "bpaul@ashiverb-security.com",
//   password: "update@@#",
//   role: "customer",
// },
// {
//   username: "eSanusi",
//   email: "elmsatuel@nnu.com",
//   password: "aline@45uu.0",
//   role: "worker",
// }];

// { "username": "eSanusi", "firstName": "Jaanai", "lastName": "Akmel", "email": "elmsatuel@ashiverb-security.com", "phone": "02133445678", "password": "cusT2@34r@", "role": "customer" }
// [
//   {
//     username: "yAremu",
//     firstName: "Yakubu",
//     lastName: "Aremu",
//     email: "sa.yakubu@perrycleans.com",
//     phone: "08030000001",
//     password: "User@12345",
//     role: "super_admin",
//   },
//   {
//     username: "tAkin",
//     firstName: "Tola",
//     lastName: "Akin",
//     email: "admin.tola@perrycleans.com",
//     phone: "08030000002",
//     password: "my@!User@12345",
//     role: "admin",
//   },
//   {
//     username: "cNwosu",
//     firstName: "Chika",
//     lastName: "Nwosu",
//     email: "Nwosu.chika@perrycleans.com",
//     phone: "08030000003",
//     password: "!User@12345",
//     role: "admin",
//   },
//   {
//     username: "mBello",
//     firstName: "Musa",
//     lastName: "Bello",
//     email: "mBello@perrycleans.com",
//     phone: "08030000004",
//     password: "!UseMusar@12345",
//     role: "admin",
//   },
//   {
//     username: "iOkoro",
//     firstName: "Ifeanyi",
//     lastName: "Okoro",
//     email: "iOkoro@perrycleans.come@perrycleans.com",
//     phone: "08030000005",
//     password: "User@00-0++5",
//     role: "worker",
//   },
//   {
//     username: "zSani",
//     firstName: "Zainab",
//     lastName: "Sani",
//     email: "zSani@perrycleans.com",
//     phone: "08030000006",
//     password: "9837huy#$$",
//     role: "worker",
//   },
//   {
//     username: "kAde",
//     firstName: "Kemi",
//     lastName: "Ade",
//     email: "kAde@perrycleans.com",
//     phone: "08030000007",
//     password: "!!@User@***jd",
//     role: "worker",
//   },
//   {
//     username: "dEze",
//     firstName: "Daniel",
//     lastName: "Eze",
//     email: "dEz9@perrycleans.com",
//     phone: "08030000008",
//     password: "!!@deze@***jd",
//     role: "worker",
//   },
//   {
//     username: "aLawal",
//     firstName: "Amina",
//     lastName: "Lawal",
//     email: "aLawal@perrycleans.com",
//     phone: "08030000009",
//     password: "!!@aLawal@***jd",
//     role: "worker",
//   },
//   {
//     username: "tAjayi",
//     firstName: "Tunde",
//     lastName: "Ajayi",
//     email: "tAjayi@perrycleans.com",
//     phone: "08030000010",
//     password: "!!@tAjayi@***jd",
//     role: "customer",
//   },
//   {
//     username: "fBukar",
//     firstName: "Fatima",
//     lastName: "Bukar",
//     email: "fBukar@perrycleans.com",
//     phone: "08030000011",
//     password: "!!@fBukar@***jd",
//     role: "customer",
//   },
//   {
//     username: "eUmeh",
//     firstName: "Emeka",
//     lastName: "Umeh",
//     email: "!!@eUmeh@***jd@perrycleans.com",
//     phone: "08030000012",
//     password: "!!@eUmeh@***jd",
//     role: "customer",
//   },
//   {
//     username: "gIbe",
//     firstName: "Grace",
//     lastName: "Ibe",
//     email: "gIbe@perrycleans.com",
//     phone: "08030000013",
//     password: "!!@gIbe@***jd",
//     role: "customer",
//   },
//   {
//     username: "hYusuf",
//     firstName: "Hassan",
//     lastName: "Yusuf",
//     email: "cust.hassan@perrycleans.com",
//     phone: "08030000014",
//     password: "User@12345",
//     role: "customer",
//   },
//   {
//     username: "nNnamdi",
//     firstName: "Ngozi",
//     lastName: "Nnamdi",
//     email: "nNnamdi@perrycleans.com",
//     phone: "08030000015",
//     password: "!!@nNnamdi@***jd",
//     role: "customer",
//   },
//   {
//     username: "bAlabi",
//     firstName: "Bayo",
//     lastName: "Alabi",
//     email: "cust.bayo@perrycleans.com",
//     phone: "08030000016",
//     password: "User@12345",
//     role: "customer",
//   },
//   {
//     username: "cust_rebecca",
//     firstName: "Rebecca",
//     lastName: "Edet",
//     email: "cust.rebecca@perrycleans.com",
//     phone: "08030000017",
//     password: "User@12345",
//     role: "customer",
//   },
//   {
//     username: "cust_ibrahim",
//     firstName: "Ibrahim",
//     lastName: "Garba",
//     email: "cust.ibrahim@perrycleans.com",
//     phone: "08030000018",
//     password: "User@12345",
//     role: "customer",
//   },
//   {
//     username: "cust_sade",
//     firstName: "Sade",
//     lastName: "Ojo",
//     email: "cust.sade@perrycleans.com",
//     phone: "08030000019",
//     password: "User@12345",
//     role: "customer",
//   },
//   {
//     username: "sOjo",
//     firstName: "Sade",
//     lastName: "Ojo",
//     email: "cust.sade@perrycleans.com",
//     phone: "08030000256",
//     password: "User@12345",
//     role: "customer",
//   },
//   {
//     username: "kObi",
//     firstName: "Kelvin",
//     lastName: "Obi",
//     email: "cust.kelvin@perrycleans.com",
//     phone: "+2348123456789",
//     password: "User@12345",
//     role: "customer",
//   },
//   {
//     username: "rBamgbose",
//     firstName: "Ronke",
//     lastName: "Bamgbose",
//     email: "cust.ronke@perrycleans.com",
//     phone: "+2348123456799 ",
//     password: "",
//     role: "",
//     status: "",
//   },
//   {
//     username: "",
//     firstName: "",
//     lastName: "",
//     email: "",
//     phone: "",
//     password: "",
//     role: "",
//     status: "",
//   },
//   {
//     username: "",
//     firstName: "",
//     lastName: "",
//     email: "",
//     phone: "",
//     password: "",
//     role: "",
//     status: "",
//   },
// ];
